export const PROVIDERS = {
  cursor: {
    provider: 'cursor',
    providerTags: ['cursor'],
    configDir: '.cursor',
    displayName: 'Cursor',
    frontmatterFields: ['license'],
  },
  'claude-code': {
    provider: 'claude-code',
    providerTags: ['claude-code', 'claude'],
    configDir: '.claude',
    displayName: 'Claude Code',
    frontmatterFields: ['user-invocable', 'argument-hint', 'license', 'allowed-tools'],
  },
  gemini: {
    provider: 'gemini',
    providerTags: ['gemini'],
    configDir: '.gemini',
    displayName: 'Gemini',
    frontmatterFields: [],
  },
  codex: {
    provider: 'codex',
    providerTags: ['codex'],
    configDir: '.codex',
    displayName: 'Codex',
    frontmatterFields: [],
  },
  agents: {
    provider: 'agents',
    providerTags: ['agents', 'codex'],
    configDir: '.agents',
    displayName: 'Codex Repo Skills',
    placeholderProvider: 'codex',
    frontmatterFields: [],
  },
  github: {
    provider: 'github',
    providerTags: ['github'],
    configDir: '.github',
    displayName: 'GitHub Copilot',
    placeholderProvider: 'agents',
    frontmatterFields: ['user-invocable', 'argument-hint', 'license'],
  },
  kiro: {
    provider: 'kiro',
    providerTags: ['kiro'],
    configDir: '.kiro',
    displayName: 'Kiro',
    frontmatterFields: ['license'],
  },
  opencode: {
    provider: 'opencode',
    providerTags: ['opencode'],
    configDir: '.opencode',
    displayName: 'OpenCode',
    frontmatterFields: ['user-invocable', 'argument-hint', 'license', 'allowed-tools'],
  },
  pi: {
    provider: 'pi',
    providerTags: ['pi'],
    configDir: '.pi',
    displayName: 'Pi',
    frontmatterFields: ['license', 'allowed-tools'],
  },
  qoder: {
    provider: 'qoder',
    providerTags: ['qoder'],
    configDir: '.qoder',
    displayName: 'Qoder',
    frontmatterFields: ['user-invocable', 'argument-hint', 'license', 'allowed-tools'],
  },
  'trae-cn': {
    provider: 'trae-cn',
    providerTags: ['trae-cn', 'trae'],
    configDir: '.trae-cn',
    displayName: 'Trae China',
    placeholderProvider: 'trae',
    frontmatterFields: ['user-invocable', 'argument-hint', 'license'],
  },
  trae: {
    provider: 'trae',
    providerTags: ['trae'],
    configDir: '.trae',
    displayName: 'Trae',
    frontmatterFields: ['user-invocable', 'argument-hint', 'license'],
  },
  'rovo-dev': {
    provider: 'rovo-dev',
    providerTags: ['rovo-dev'],
    configDir: '.rovodev',
    displayName: 'Rovo Dev',
    frontmatterFields: ['user-invocable', 'argument-hint', 'license', 'allowed-tools'],
  },
};
